import { writeFileSync } from "node:fs";
import { isAbsolute, join, relative } from "node:path";
import { loadConfig } from "../config-loader.ts";
import { findProject } from "../project.ts";
import { resolveProject } from "../resolve.ts";
import { printWarnings } from "./output.ts";

const quote = (value: string): string =>
  /^[A-Za-z0-9_.:/@=-]*$/.test(value) ? value : `'${value.replace(/'/g, `'\\''`)}'`;

const USAGE = `usage: autoport env [--json] [--export] [--write <file>]

  --json           print a JSON object
  --export         prefix each line with "export "
  --write <file>   write a dotenv file, for tools that cannot be wrapped
`;

export const envCommand = async (args: string[]): Promise<number> => {
  if (args.includes("--help") || args.includes("-h")) {
    process.stdout.write(USAGE);
    return 0;
  }

  const write = args.indexOf("--write");
  const target = write === -1 ? undefined : args[write + 1];
  if (write !== -1 && !target) {
    process.stderr.write(USAGE);
    return 2;
  }

  const unknown = args.find(
    (arg, index) =>
      arg.startsWith("-") &&
      !["--json", "--export", "--write"].includes(arg) &&
      args[index - 1] !== "--write",
  );
  if (unknown) {
    process.stderr.write(`autoport: unknown flag ${unknown}\n\n${USAGE}`);
    return 2;
  }

  const layout = findProject();
  const project = resolveProject({ layout, config: await loadConfig(layout.root) });
  printWarnings(project.warnings);

  if (args.includes("--json")) {
    process.stdout.write(`${JSON.stringify(project.resources, null, 2)}\n`);
    return 0;
  }

  const prefix = args.includes("--export") ? "export " : "";
  const lines = Object.entries(project.resources)
    .map(([key, value]) => `${prefix}${key}=${quote(String(value))}`)
    .join("\n");

  if (target) {
    const path = isAbsolute(target) ? target : join(process.cwd(), target);
    writeFileSync(path, `# Generated by autoport. Regenerate with: autoport env --write ${target}\n${lines}\n`);
    process.stderr.write(`autoport: wrote ${relative(process.cwd(), path)}\n`);
    return 0;
  }

  process.stdout.write(`${lines}\n`);
  return 0;
};
