import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ResolvedProject } from "./types.ts";

export const TYPES_FILE = "autoport-env.d.ts";

/** The published name, which is what generated augmentations must target. */
const PACKAGE = "@mr96/autoport";

/**
 * Teach TypeScript what this project's values are, twice.
 *
 * `process.env` is the augmentation that matters most, because it is the one
 * that needs nothing at runtime: a project reading `process.env.DATABASE_URL`
 * has no import to resolve, so autoport stays a dev dependency and a deployed
 * build that pruned it still starts. Nothing imports this file — a `.d.ts` in
 * the program contributes globally, as `next-env.d.ts` does.
 *
 * The module augmentation stays for `resources` and `services`, which give a
 * number where the environment can only give a string, and throw on a missing
 * key rather than yielding undefined. That surface needs the package installed
 * at runtime, so it is the reason to make autoport a real dependency.
 */
/**
 * Is autoport a dependency of this project, as opposed to something that ran
 * through npx?
 *
 * `declare module "@mr96/autoport"` only compiles when the module resolves, so
 * emitting it unconditionally makes the generated file fail to type-check in
 * exactly the projects that keep autoport out of their dependencies — the file
 * whose whole purpose is to let them.
 */
const installed = (project: ResolvedProject): boolean =>
  [project.appDir, project.key].some((dir) =>
    existsSync(join(dir, "node_modules", ...PACKAGE.split("/"))),
  );

export const renderTypes = (project: ResolvedProject): string => {
  const resources = Object.entries(project.resources)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([key, value]) =>
        `    ${JSON.stringify(key)}: ${typeof value === "number" ? "number" : "string"};`,
    )
    .join("\n");

  const services = Object.keys(project.services)
    .sort()
    .map((name) => `    ${JSON.stringify(name)}: import(${JSON.stringify(PACKAGE)}).ResolvedService;`)
    .join("\n");

  // An empty body would make `Resources` widen back to a plain record, so a
  // project with nothing inferred says so explicitly.
  const body = resources || "    // nothing inferred yet";
  const serviceBody = services || "    // nothing inferred yet";

  // Every environment variable is a string, whatever the value's own type:
  // `process.env` holds strings, and typing a port as a number here would be a
  // lie that only shows up as arithmetic on "40001".
  const ambient = Object.keys(project.resources)
    .sort()
    .map((key) => `      ${JSON.stringify(key)}: string;`)
    .join("\n");
  const ambientBody = ambient || "      // nothing inferred yet";

  return `// Generated by autoport. Do not edit.
// Rewritten automatically whenever autoport resolves this project.

declare global {
  namespace NodeJS {
    interface ProcessEnv {
${ambientBody}
    }
  }
}

${
    installed(project)
      ? `declare module ${JSON.stringify(PACKAGE)} {
  interface Resources {
${body}
  }

  interface Services {
${serviceBody}
  }
}
`
      : `// ${PACKAGE} is not a dependency here, so only process.env is typed.
// Add it to use \`resources\` and \`services\`, which need it at runtime.
`
  }
export {};
`;
};

export const writeTypes = (project: ResolvedProject): string => {
  const path = join(project.appDir, TYPES_FILE);
  writeFileSync(path, renderTypes(project));
  return path;
};
