import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ResolvedProject } from "./types.ts";

export const TYPES_FILE = "autoport-env.d.ts";

/** The published name, which is what generated augmentations must target. */
const PACKAGE = "@mr96/autoport";

/**
 * Teach TypeScript what `resources.X` holds.
 *
 * Module augmentation rather than a generated module keeps the import short:
 * `import { resources } from "@mr96/autoport"` stays typed without importing config.
 */
export const renderTypes = (project: ResolvedProject): string => {
  const resources = Object.entries(project.resources)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([key, value]) =>
        `    ${JSON.stringify(key)}: ${typeof value === "number" ? "number" : "string"};`,
    )
    .join("\n");

  const services = Object.keys(project.services)
    .sort()
    .map((name) => `    ${JSON.stringify(name)}: import(${JSON.stringify(PACKAGE)}).ResolvedService;`)
    .join("\n");

  // An empty body would make `Resources` widen back to a plain record, so a
  // project with nothing inferred says so explicitly.
  const body = resources || "    // nothing inferred yet";
  const serviceBody = services || "    // nothing inferred yet";

  return `// Generated by autoport. Do not edit.
// Rewritten automatically whenever autoport resolves this project.

declare module ${JSON.stringify(PACKAGE)} {
  interface Resources {
${body}
  }

  interface Services {
${serviceBody}
  }
}

export {};
`;
};

export const writeTypes = (project: ResolvedProject): string => {
  const path = join(project.appDir, TYPES_FILE);
  writeFileSync(path, renderTypes(project));
  return path;
};
